import { Inter } from 'next/font/google'
import './globals.css'
import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  a: 'a',
  sdf: 'a',
  a: 'a',
  a: 'a',
  a: 'a',
  a: 'a',
  a: 'a',
  a: 'a',
  a: 'a',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <h2>hihi</h2>
      </body>
    </html>
  )
}
